version: '3.8'

services:
  instagram-reels-microservice:
    build: .
    container_name: instagram-reels-microservice
    ports:
      - "5001:5001"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=5001
      - DEBUG=false
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
      - INSTAGRAM_USE_LOGIN=true
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservice-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: instagram-reels-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - instagram-reels-microservice
    networks:
      - microservice-network
    restart: unless-stopped
    profiles:
      - production

networks:
  microservice-network:
    driver: bridge